# This file was generated by GoReleaser. DO NOT EDIT.
class Natscmd < Formula
  desc "Simple NATS client for quick and dirty manual configuration testing"
  homepage "https://github.com/tanelmae/natscmd"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/tanelmae/natscmd/releases/download/v0.1.3/natscmd_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "153bc8e39801f485aa239d168bdaf4aada91531085e6e0ace70d96534c85324a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/tanelmae/natscmd/releases/download/v0.1.3/natscmd_0.1.3_Linux_x86_64.tar.gz"
      sha256 "ee5179f2d209cfa03430ceb65d6db22e5109b0d8d1df6460bd4c706d31a392d5"
    end
  end

  def install
    bin.install "natscmd"
  end

  test do
    system "#{bin}/natscmd -v"
  end
end
